version: '3'
services:
  backend-api-container:
    container_name: backend-api-container
    build:
      context: .
      dockerfile: .
    ports:
      - 8000:8000
    working_dir: /app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USERNAME: admin
      DB_PASSWORD: admin
      APP_ENV: dev
    volumes:
      - ./:/app
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

volumes:
  db-store:
  vendor-package:
    driver: local
